# Generated by Django 2.2 on 2019-04-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoliceNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.NullBooleanField()),
                ('ownership', models.ForeignKey(db_column='ownership', on_delete=django.db.models.deletion.CASCADE, related_name='police_number_user', to=settings.AUTH_USER_MODEL)),
                ('police_number', models.ForeignKey(db_column='police_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_number_user', to='reports.PoliceNumber')),
                ('vehicle', models.ForeignKey(db_column='vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='police_number_user', to='reports.Vehicle')),
            ],
            options={
                'verbose_name': 'Nomor Polisi Pengguna',
                'verbose_name_plural': 'Nomor Polisi Pengguna',
                'db_table': 'users_police_number',
                'ordering': ['-date_created'],
                'unique_together': {('ownership', 'police_number', 'vehicle')},
            },
        ),
    ]
