# Generated by Django 2.2 on 2019-04-15 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_auto_20190411_1451'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoliceNumberClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_number', models.CharField(max_length=255, null=True)),
                ('file_certificate_vehicle', models.FileField(blank=True, max_length=500, null=True, upload_to='claimed/certificate-vehicle')),
                ('file_certificate_ownership', models.FileField(blank=True, max_length=500, null=True, upload_to='claimed/certificate-ownership')),
                ('file_identity_card', models.FileField(blank=True, max_length=500, null=True, upload_to='claimed/identity-card')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('claimant', models.ForeignKey(db_column='claimant', on_delete=django.db.models.deletion.CASCADE, related_name='police_number_claim', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(db_column='vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='police_number_claim', to='reports.Vehicle')),
            ],
            options={
                'verbose_name': 'Klaim Nomor Polisi',
                'verbose_name_plural': 'Klaim Nomor Polisi',
                'db_table': 'users_claim',
                'ordering': ['-date_created'],
                'unique_together': {('claimant', 'police_number', 'vehicle')},
            },
        ),
    ]
