# Generated by Django 2.2 on 2019-04-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpolicenumberclaim_is_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpolicenumberclaim',
            old_name='is_accept',
            new_name='is_accepted',
        ),
    ]
