# Generated by Django 2.2 on 2019-04-16 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190416_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicenumberclaim',
            name='police_number',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)+$')]),
        ),
    ]
