# Generated by Django 2.2 on 2019-04-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
        ('users', '0008_auto_20190416_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpolicenumberclaim',
            name='file_certificate_ownership',
        ),
        migrations.RemoveField(
            model_name='userpolicenumberclaim',
            name='file_certificate_vehicle',
        ),
        migrations.RemoveField(
            model_name='userpolicenumberclaim',
            name='file_identity_card',
        ),
        migrations.CreateModel(
            name='UserClaimFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_claim_file', to='users.UserPoliceNumberClaim')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_claim_file', to='mains.FileManagement')),
            ],
            options={
                'db_table': 'users_claim_file',
                'ordering': ['-date_created'],
            },
        ),
    ]
