# Generated by Django 2.2 on 2019-04-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190420_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclaimfile',
            old_name='file',
            new_name='file_management',
        ),
    ]
