# Generated by Django 2.2 on 2019-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190420_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclaimfile',
            name='file_type',
            field=models.PositiveIntegerField(choices=[(0, 'Jenis file'), (1, 'KTP'), (2, 'BPKB'), (3, 'STNK')], null=True),
        ),
    ]
