# Generated by Django 2.2 on 2019-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userclaimfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclaimfile',
            name='file_type',
            field=models.PositiveIntegerField(choices=[(1, 'KTP'), (2, 'BPKB'), (3, 'STNK')], null=True),
        ),
    ]
