# Generated by Django 2.2 on 2019-04-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_claimed', models.NullBooleanField()),
                ('reporter', models.ForeignKey(db_column='reporter', on_delete=django.db.models.deletion.CASCADE, related_name='police_number_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nomor Polisi',
                'verbose_name_plural': 'Nomor Polisi',
                'db_table': 'reports_police_number',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Jenis Kendaraan',
                'verbose_name_plural': 'Jenis Kendaraan',
                'db_table': 'reports_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Pelanggaran',
                'verbose_name_plural': 'Pelanggaran',
                'db_table': 'reports_violation',
            },
        ),
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, max_length=500, null=True)),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='picture/')),
                ('location', models.TextField(blank=True, max_length=500, null=True)),
                ('location_lat', models.CharField(blank=True, max_length=255, null=True)),
                ('location_lon', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('police_number', models.ForeignKey(db_column='police_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='reports.PoliceNumber')),
                ('reporter', models.ForeignKey(db_column='reporter', on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(db_column='violation', on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='reports.Violation')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'db_table': 'reports_reported',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='policenumber',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='police_number_reported', to='reports.Vehicle'),
        ),
    ]
