# Generated by Django 2.2 on 2019-04-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='police_number',
            field=models.ForeignKey(db_column='police_number', on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='reports.PoliceNumber'),
        ),
    ]
