# Generated by Django 2.2 on 2019-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190411_0723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='policenumber',
            unique_together={('vehicle', 'number')},
        ),
    ]
