# Generated by Django 2.2 on 2019-04-16 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190411_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policenumber',
            name='number',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
