# Generated by Django 2.2 on 2019-04-16 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190416_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policenumber',
            name='number',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
