# Generated by Django 2.2 on 2019-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20190416_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='policenumber',
            name='is_onclaim',
            field=models.NullBooleanField(),
        ),
    ]
