# Generated by Django 2.2 on 2019-04-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_auto_20190425_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagementtype',
            name='is_active',
            field=models.NullBooleanField(),
        ),
    ]
