# Generated by Django 2.2 on 2019-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_filemanagementtype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagementtype',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
